specfile_path: tools/fedora/dbcsr.spec
files_to_sync:
  - src: tools/fedora/
    dest: ./
    delete: true
    filters:
      - "protect .git*"
      - "protect sources"
      - "protect changelog"
      - "- plans/rpminspect"
      - "- plans/rpmlint"
      # No packaged tmt jobs described yet, removing the .fmf as well
      - "- .fmf/"
  - .packit.yaml
upstream_package_name: dbcsr
downstream_package_name: dbcsr
update_release: false
upstream_tag_template: v{version}

jobs:
  - &copr_build
    job: copr_build
    trigger: release
    owner: lecris
    project: release
    targets: &targets
      - fedora-all-x86_64
      - fedora-all-aarch64
  - <<: *copr_build
    trigger: commit
    branch: master
    project: nightly
    additional_repos:
      - copr://@scikit-build/release
  - &tests
    job: tests
    trigger: commit
    targets: *targets
    fmf_path: tools/fedora
  - <<: *copr_build
    trigger: pull_request
    project: dbcsr
    update_release: true
    release_suffix: "{PACKIT_RPMSPEC_RELEASE}"
  - <<: *tests
    trigger: pull_request
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
