default_language_version:
    python: python3

exclude: '^tools/(build_utils/fypp)'
fail_fast: false
repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-ast
  - id: check-yaml
- repo: https://github.com/pseewald/fprettify
  rev: v0.3.6
  hooks:
  - id: fprettify
- repo: local
  hooks:
  - id: check-header
    name: check file headers
    entry: ./.pre-commit/check_header.py --verbose
    language: script
    types: [text]
    exclude: '^(tools|.cp2k)/'
  - id: check-doxygen-tags
    name: no doxygen tags present
    entry: '^\s*!>'
    language: pygrep
    types: [text]
